"""empty message

Revision ID: e4f5d01d36ff
Revises: ca1461d31fd0
Create Date: 2020-05-06 12:45:20.658716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f5d01d36ff'
down_revision = 'ca1461d31fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actor', 'height')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('height', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
